### ISSUE TITLE
Special comparison for JSON data type

### ISSUE THREAD

**Issue by kevinsmith** [atlasphp/Atlas.Table#2]
@pmjones, wanted to see if you'd be open to this enhancement before I actually dive in and work on it. Here's the situation:

When a table makes use of the JSON data type in MySQL (and perhaps other RDBMS, I haven't tested them), Atlas routinely tries to update a record that actually has no change (which throws the ol' _Expected 1 row affected, actual 0._ exception). The reasons:

1. MySQL does not guarantee it will return JSON strings with the same spacing as was used when the string was inserted into the DB, and
2. MySQL does not guarantee it will return JSON strings with properties ordered the same as was used when the string was inserting into the DB. [Ref](https://stackoverflow.com/a/48382771/1217620)

The first issue can be side-stepped by decoding and re-encoding the JSON in PHP in a `modifySelectedRow()` table event, but I don't believe the second can be dealt with anywhere other than in the place [where the comparison is done to determine if the data has changed](https://github.com/atlasphp/Atlas.Table/blob/1.x/src/Row.php#L193).

Would you be open to a PR that incorporates special JSON comparison for JSON data types?

**Comment by pmjones** [comment]
> Where is the info that fills out the Table::COLUMNS constant being used?

Nowhere; I included it because I imagined it could be used by, say, a data filtering mechanism that needed column information. `DRIVER` likewise is not used, though `COLUMN_DEFAULTS` is used when you call `newRow()`.

/me ponders

In theory, you should be able to hook into `TableEvents::before(Insert|Update)Row()` and do comparisons there, reordering the JSON data as you see fit in the `$row`. The `$table` method param will give you quick access to the constants a la `$table::COLUMNS`, and you should be able to see the initial Row data arrangement using `$row->getArrayInit()`.

Do those bits of information begin to help?

**Comment by pmjones** [comment]
As a side note, please be aware that I have been putting together a domain-object mapper system called [Atlas.Transit](https://github.com/atlasphp/Atlas.Transit) that may help to soothe some of these woes, though more in the domain layer than in the persistence layer. Value Objects, like the JSON object you are dealing with now, are the last major part; though they are proving resistant to my efforts, I think I'm getting closer now.

**Comment by kevinsmith** [comment]
Looking forward to Transit, for sure! This particular issue seems to be one that should be solved in the persistence layer though, right?

> In theory, you should be able to hook into `TableEvents::before(Insert|Update)Row()` and do comparisons there, reordering the JSON data as you see fit in the `$row`.

Right, I've got a solution that's working in our app, but this feels like something the ORM should handle. No?

In short, Atlas thinks something has changed so it issues a query to persist that change, and then it finds out that, actually, nothing changed at all. So it throws an exception. As as user, of the library, that seems like a bug to me.

**Comment by froschdesign** [comment]
@kevinsmith 
> 1. MySQL does not guarantee it will return JSON strings with the same spacing as was used when the string was inserted into the DB, and
> 2. MySQL does not guarantee it will return JSON strings with properties ordered the same as was used when the string was inserting into the DB.

I think this problem is related to:

* https://github.com/atlasphp/Atlas.Mapper/issues/1
* https://github.com/atlasphp/Atlas.Orm/pull/95

**Comment by kevinsmith** [comment]
@froschdesign I don't believe the issue is related to those at all. Those are both concerning the problem of Atlas's identityMap being unaware that something in the database has changed and continuing to use the outdated row data.

The problem I'm raising is entirely different. A simple example:

1. Retrieve a record from the database that includes a column with MySQL's JSON data type.
2. Perform `$record->json_field = json_encode(json_decode($record->json_field));`
3. Persist the record.
4. Get `Expected 1 row affected, actual 0.` exception.

This is all because MySQL and PHP format that JSON string differently. So even though the data actually hasn't changed at all, Atlas thinks it has and issues a query to update it at the database. Then it throws an exception.

**Comment by froschdesign** [comment]
@kevinsmith 
Sorry, I had only in mind the `INSERT` from your initial post:

> when the string was inserted into the DB

After that, a refresh could have been a possible solution.

---

Please don't get me wrong, I used also the JSON datatype in some databases and this issue report is also important for me.
I still think that class `Row` as the place to solve a _database type problem_ is the wrong place - too far away from the database and the classes that are responsible for it.

Therefore I would answer here with no:

> > In theory, you should be able to hook into TableEvents::before(Insert|Update)Row() and do comparisons there, reordering the JSON data as you see fit in the $row.
>
> Right, I've got a solution that's working in our app, but this feels like something the ORM should handle.

**Comment by kevinsmith** [comment]
Hmm. Your reply got me thinking... while MySQL highlights this issue, I wonder if it's not _actually_ a database concern. Let's take the database out of the picture entirely.

Take these JSON objects, for example:

- `{name: "John", age: 31, city: "New York"}`
- `{age:31,city:"New York",name:"John"}`

The _representation_ of the object is different, but the actual _value_ of it is identical.

`Row` already has the responsibility of determining whether a value has been modified when the calling class tries [setting a column value](https://github.com/atlasphp/Atlas.Table/blob/1.x/src/Row.php#L170). When it comes to JSON objects, clearly a string comparison isn't enough to determine equality. So even ignoring the database entirely, perhaps `Row:: isModified ()` should check strings to see if they're JSON objects, and if so, run a special comparison on them? (Just like it's already doing for numeric types.)

**Comment by froschdesign** [comment]
> Let's take the database out of the picture entirely.
> …
> When it comes to JSON objects…

…which is not handle, because at the moment only pure / _normal_ strings are covered. If you want it that way: a JSON string is a _special_ string and it is not covered in the `Row` class.
And if you allow JSON as _special_ string for comparison, then don't forget YAML, TOML, JSON5 and so on. 😉

**Comment by pmjones** [comment]
The JSON thing really is a problem. The string representation of the re-encoded JSON *has in fact changed* in memory, even though the thing represented by the string has not.

There's a similar problem with floats and decimals. If you have a column as `DECIMAL(10,2)`, fetch a value with two decimal places (`1.23`), and end up adding a 3rd decimal place somehow (`1.234`), PHP will correctly see that as an in-memory change and send the update to MySQL. But MySQL silently truncates extract decimal places, sees the same number as before, and does not update the column, giving "0 rows affected 1 expected".

These kinds of tricky details only get more expansive, not less. (Date & time handling is one area of that.) And it gets tricky on a per-database-backend basis. That means any solution added to the Row for this problem, sets a precedent for adding other solutions to the Row for related problems, and thereby greatly enlarging the scope of the Row class.

With all that in mind, I have to go back to m previous suggestion of using TableEvents for this. I realize now that the feature I'm about to describe is completely undocumented, and I need to remedy that. Meanwhile:

The `TableEvents::beforeUpdateRow()` method has a `?array` return signature. If it returns null, then the `Table::update()` method will run `Row::getArrayDiff()` to get the array differences to send to the database. But if `TableEvents::beforeUpdateRow()` method returns an array instead, that array will be used as the differences to send to the database, and Row::getArrayDiff() never gets called. That logic is there so you can drop a filtering system into TableEvents and use it to validate and sanitize the values going to the database, without modifying the Row values themselves.

So what you will want to do here is something like this:

```php
class FooTableEvents
{
    public function beforeUpdateRow($table, $row) : ?array
    {
        $old = $row->getArrayInit();
        $new = $row->getArrayDiff();
        foreach ($new as $key => $val) {
            if (
                $table::COLUMN[$key]['type'] === 'json'
                && ! $this->isJsonModified($old[$key], $new[$key])
            ) {
                unset($diff[$key]);
            }
        }

        return $new;
    }

    // code from Kevin Smith
    private function isJsonModified(?string $old, ?string $new) : bool
    {
        if ($old === null && $new === null) {
            return false;
        }

        if ($old === null || $new === null) {
            return true;
        }

        $oldObject = \json_decode($old);
        $oldDecodeHasError = (json_last_error() !== JSON_ERROR_NONE);

        $NewObject = \json_decode($new);
        $newDecodeHasError = (json_last_error() !== JSON_ERROR_NONE);

        if ($oldDecodeHasError && $newDecodeHasError) {
            return $old !== $new; // both decodes hit errors, compare original inputs strictly
        }

        return $oldObject != $NewObject; // compare loosely to check for same attributes and values
    }
}
```

You might even turn it into a trait, or use it in a base class, for your TableEvents.

I know this is not really the solution you want, but it's the best one I can think of that keeps the Row from getting too unwieldy.

Please let me know how this works for you, if at all.

**Comment by kevinsmith** [comment]
Yes! That is indeed what I need. And given all the cases and platforms that would need to be accounted for, it makes sense to not try to bake this into the ORM itself.

Sadly, my team is working with 1.x which doesn't have Table Events. Looks like we've got another reason to upgrade soon.

Thanks for the insight!

**Comment by pmjones** [comment]
Yes, I think upgrading is the way to go.

Having said that, both 1.x and 2.x have TableEvents. Further, the beforeInsert() and beforeUpdate() methods are not return-typehinted, so returning something from them would not technically be a BC break. So, a change to allow them to return an array for insert/update like 3.x does, is easy to hypothesize. Cannot promise when that might be done, though, if at all.

**Comment by pmjones** [comment]
Pending further commentary, I am closing this issue, reserving the right to reopen it as needed.

Thanks @kevinsmith and @froschdesign for your discussion here!
