### ISSUE TITLE
Why the Row construct is a final method?

### ISSUE THREAD

**Issue by consatan** [atlasphp/Atlas.Table#7]
I want to change something in the construct method, but it's final method, is a mistake?

All Atlas project class method is not final but only this class.

**Comment by froschdesign** [comment]
@consatan 
> Why the Row construct is a final method
> …
> I want to change something in the construct method…

The other way around: why would you like to change the constructor? Can you explain your use case? Thanks!

**Comment by consatan** [comment]
@froschdesign 

I change the `Atlas CLI` template file `TypeRow.tpl`, so the generated `TypeRow.php` can extends my custom `Row` class. 

In my custom `Row` class, I allow user access `Row` column with two way, e.g.
```php
$user = $atlas->fetchRecrod(User::class, 1);
echo $user->full_name; // or $user->fullName;
```

And now I want return real data type when user access `Row` column, e.g.
```php
echo $user->age; // now return (string)"25", expect (int)25
```

Here have two implementations in my mind:
- set the real data type in `construct` method, base on `TypeTable::COLUMNS`.
- when user access the column, dynamic return real data type also base on `TypeTable::COLUMNS`, of course we can cached this column real datatype.

**Comment by froschdesign** [comment]
@consatan 
> And now I want return real data type when user access `Row` column, e.g.
> 
> `echo $user->age; // now return (string)"25", expect (int)25`

Try to set the attributes for handling the database data:

* `PDO::ATTR_STRINGIFY_FETCHES`
* `PDO::ATTR_EMULATE_PREPARES`

See: https://php.net/manual/pdo.setattribute.php

You can use the fourth parameter of `new` for this:

```php
$atlas = Atlas\Orm\Atlas::new('sqlite::memory', null, null, [
    PDO::ATTR_EMULATE_PREPARES => false,
    PDO::ATTR_STRINGIFY_FETCHES => false,
]);
```

No other changes are needed and you should get the desired value as integer – based on the datatype of the database table.

**Comment by consatan** [comment]
@froschdesign 

It's work, thx!

**Comment by consatan** [comment]
@froschdesign 
I reopen this issue, because I still don't understand why make Row::__construct as a final method.

Why not allow developer override this method? Could you please explain the benefits of this implementations?

**Comment by froschdesign** [comment]
@consatan 
> Why not allow developer override this method?

It is quite simple: the keyword `final` ensures that the class / method works as expected.
Overriding the constructor in userland code may affect the entire use of this library.

If the signature of the constructor has changed, the following lines will no longer work:

https://github.com/atlasphp/Atlas.Table/blob/4c82ae75df1b04d7afadeab5ae0b421f7c8941d7/src/Table.php#L260-L264

Background:

> Unlike with other methods, PHP will not generate an `E_STRICT` level error message when `__construct()` is overridden with different parameters than the parent `__construct()` method has. 

https://php.net/manual/language.oop5.decon.php

**Comment by froschdesign** [comment]
@consatan 
Please keep in mind this library is based on the "Table data gateway" design pattern and the `Row` and the `Table` classes are a mapping of a database table, which includes the access to the data.
No more, no less.

So the question still stands: why do you want to change the constructor? Or what do you have in mind with these classes?
It seems that you want to extend the classes for other purposes.

**Comment by pmjones** [comment]
This appears resolved; please re-open if not!
