### ISSUE TITLE
HowTo: convert types between persistence and domain model

### ISSUE THREAD

**Issue by ulfw** [atlasphp/Atlas.Table#8]
In my case:

an array in domain model is persisted to a serialized string, so the skeleton generator defines the field as null or string.

'array_property' => [
            'name' => 'array_property',
            'type' => 'longtext',
            'size' => 4294967295,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],

in TableEvents.php, when I unserialize this property in function "modifySelectedRow", 
I immidately get the error/exception
`Atlas\Table\Exception: Expected type scalar or null; got stdClass instead`

How can this be resolved?

**Comment by froschdesign** [comment]
@ulfw 
> an array in domain model is persisted to a serialized string
> …
> when I unserialize this property

Can you explain how to serialize and unserialize the property?

**Comment by ulfw** [comment]
I´m using un/serialize(), but does it matter?

**Comment by ulfw** [comment]
Sorry to bother, any help here?

**Comment by froschdesign** [comment]
It would help if you can provide an unit test which illustrates the problem. At the moment it is hard to reproduce why there is a `stdClass`.

**Comment by ulfw** [comment]
The string in database is a serialized stdClass, like a propertybag.
Problem for me is to define this property as object, not as string.
So it´s more a design problem. How can I tell Atlas.Table, that this is a stdClass, not a string.

**Comment by froschdesign** [comment]
Now things are getting clearer!

> How can I tell Atlas.Table, that this is a stdClass, not a string.

A table gateway object represents a database table and if the column is defined as string in the database then it must be the same in the table gateway object.
An option can be the record object of Atlas.Mapper. Please have a look in the chapter "[1.1.7. Record and RecordSet Behaviors](http://atlasphp.io/cassini/orm/behavior.html)" of the Atlas ORM documentation.

**Comment by pmjones** [comment]
This appears resolved; please re-open if not!
